version: '3.1'
services:
  stats-server:
    build: statistic/server/
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      [stats-db]
    environment:
      STAT_SERVER_PORT: 9090
      DB_HOST: stats-db
      DB_PORT: 5432
      DB_NAME: emw_stats_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  stats-client:
    build: statistic/client/
    container_name: ewm-stats-client
    ports:
      - "8080:8080"
    depends_on:
      [stats-server]
    environment:
      - STAT_CLIENT_PORT=8080
      - STAT_SERVER_ADDRESS=http://ewm-stats:9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: emw_stats_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      hostname: emw_stats_db

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
