version: '3.1'
services:
  stats-server:
    build: statistic/server/
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      [stats-db]
    environment:
      STAT_SERVER_PORT: 9090
      DB_HOST: stats-db
      DB_PORT: 5432
      DB_NAME: emw_stats_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  stats-db:
    image: postgres:14.0-alpine
    container_name: stats-db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: emw_stats_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      hostname: emw_stats_db

  main-server:
    build: main/main-server/
    container_name: ewm-main-server
    ports:
      - "8080:8080"
      - "8091:8091"
    depends_on:
      [ main-db, stats-server ]
    environment:
      MAIN_SERVER_PORT: 8080
      STAT_SERVER_URI: http://stats-server:9090
      APP_NAME: ewm-service
      DB_HOST: emw_main_db
      DB_PORT: 5432
      DB_NAME: ewm_main_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  main-db:
    image: postgres:14.0-alpine
    container_name: main-db
    ports:
      - "6433:5432"
    environment:
      POSTGRES_DB: ewm_main_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    hostname: emw_main_db
